/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function getBuffer(): Buffer
export function plus100(input: number): number
export class EmptyClass {
  constructor()
}
